### ISSUE TITLE
Long name overlapping in small screen

### ISSUE THREAD

**Issue by dausruddin** [gibatronic/ngx-superbindex#6]
![image](https://user-images.githubusercontent.com/5763466/72259611-e0315d00-364b-11ea-99f6-54996d73f82b.png)

**Comment by gibatronic** [comment]
hey there @dausruddin!

it was supposed to clip with … when it's too long.
![demo](https://user-images.githubusercontent.com/819643/72425877-eb3dd780-3788-11ea-8aad-007e99c4f43d.png)
[client/styles/main.scss:65](https://github.com/gibatronic/ngx-superbindex/blob/master/client/styles/main.scss#L65)

so I'm curious about how that happened, because [text-overflow ellipsis](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow) is quite well supported.
